# Generated by Django 4.1.2 on 2022-10-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('occupation', models.CharField(max_length=1000)),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
